name: Build End-Device Companion Firmwares

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - '**'
  release:
    types:
      - published

concurrency:
  group: companion-firmware-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-end-device-firmwares:
    uses: ./.github/workflows/firmware-builder.yml
    with:
      firmware_type: 'companion'
      release_title_prefix: 'Companion Firmware'
      release_draft: false
      firmware_targets: >-
        ["Xiao_S3_WIO_companion_radio_usb",
        "Xiao_S3_WIO_companion_radio_ble",
        "Heltec_v3_companion_radio_usb",
        "Heltec_v3_companion_radio_ble",
        "RAK_4631_companion_radio_ble"]
